# Generated by Django 5.1.5 on 2025-01-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_rating',
        ),
    ]
