# Generated by Django 5.1.5 on 2025-02-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_remove_recipe_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipw_view_conunt',
            field=models.IntegerField(default=0),
        ),
    ]
