# Generated by Django 5.1.5 on 2025-02-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_recipe_recipw_view_conunt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipw_view_conunt',
            new_name='recipe_view_conunt',
        ),
    ]
