# Generated by Django 5.1.5 on 2025-02-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_rename_recipw_view_conunt_recipe_recipe_view_conunt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_view_conunt',
            new_name='recipe_view_count',
        ),
    ]
